### ISSUE TITLE
b2sum-rs 0.2 (rust 1.19) and GNU b2sum 8.27 outputs are different

### ISSUE THREAD

**Issue by juanfra684** [jtdowney/b2sum-rs#3]
```
$ /home/juanfra/.cargo/bin/b2sum guide.pdf 
6be856d13bb62956ea7f344d4a7bcbc588469ae939f2173d872c6c55dc37a32bce4c997882a59028bbc4417354ea68b4113f684a6cb72d546d5384286be45  guide.pdf
$ b2sum guide.pdf                         
6be856d13bb62956ea7f344d4a7bcbc5088469ae939f2173d872c6c55dc37a320bce4c997882a59028bbc44173054ea68b4113f684a6cb72d546d5384286be45  guide.pdf
```
I've attached the file, so you can compare the results: [guide.pdf](https://github.com/jtdowney/b2sum-rs/files/1201766/guide.pdf).

**Comment by oconnor663** [comment]
This looks like a hex formatting bug. The top example is failing to print leading `0`'s in its output.

**Comment by jtdowney** [comment]
Thank for reporting this and thanks @oconnor663 for submitting the fix. Sorry it took so long to get to this. I never got any notifications from Github so I only saw these recently. I've made sure to fix the notification issue going forward.
